# wengwengweng

[package]
name = "buffer"
description = "text editor"
version = "0.1.0"
authors = ["t <voygagaga@outlook.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_vm = "2.1.0"
pest_meta = "2.1.0"
regex = "1.1.2"
clipboard = "0.5.0"
lsp-types = "0.56.0"

