# wengwengweng

[package]
name = "suite"
description = "components"
version = "0.1.0"
authors = ["t <voygagaga@outlook.com>"]
edition = "2018"

[dependencies]
buffer = { path = "../buffer" }
browser = { path = "../browser" }


